version: '3.8'
services:
  app:
    build: .
    container_name: my-java-app
    working_dir: /app
    volumes:
      - .:/app  # Mounts your local project to the container
    command: [ "java", "-jar", "build/libs/burrow-0.0.1-SNAPSHOT.jar" ]

